/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package drinks;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import till.main;
/**
 *
 * @author gabri
 */
public class drinks extends javax.swing.JPanel {
    private JTable table;
    private main parent;
    /**
     * Creates new form beer
     */
    public drinks(JTable table, main parent) {
        this.table = table; // Assign the passed table reference
        this.parent = parent; // Reference to main
        initComponents();
    }
    
    public String getprice(String name){
        return parent.beermap.get(name);
    }
    
    public void addBeer(String name){
        String price = getprice(name.toLowerCase());
        
        String quantityStr = parent.getQuantityStr();// Get the quantity from the main class
        int quantity = quantityStr.isEmpty() ? 1 : Integer.parseInt(quantityStr);

        // Add the row to the table
        if(price != null){
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.addRow(new Object[]{quantity, name, price});
        }

        // Clear the quantity in the main class
        parent.clearQuantity();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        drinks = new javax.swing.JTabbedPane();
        beers = new javax.swing.JPanel();
        Beers = new javax.swing.JTabbedPane();
        SirenBeers = new javax.swing.JPanel();
        twothirds = new javax.swing.JButton();
        half = new javax.swing.JButton();
        onethird = new javax.swing.JButton();
        lumina = new javax.swing.JButton();
        mesmerist = new javax.swing.JButton();
        pastel = new javax.swing.JButton();
        shattereddream = new javax.swing.JButton();
        santo = new javax.swing.JButton();
        secondserve = new javax.swing.JButton();
        soundwave = new javax.swing.JButton();
        pomp = new javax.swing.JButton();
        stationhill = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        brokendream = new javax.swing.JButton();
        GuestBeers = new javax.swing.JPanel();
        Cans = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        twothirds.setText("2/3");
        twothirds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twothirdsActionPerformed(evt);
            }
        });

        half.setText("Half");
        half.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halfActionPerformed(evt);
            }
        });

        onethird.setText("1/3");
        onethird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onethirdActionPerformed(evt);
            }
        });

        lumina.setText("Lumina");
        lumina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luminaActionPerformed(evt);
            }
        });

        mesmerist.setText("Mesmerist");
        mesmerist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesmeristActionPerformed(evt);
            }
        });

        pastel.setText("Pastel");
        pastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastelActionPerformed(evt);
            }
        });

        shattereddream.setText("Shattered Dream");
        shattereddream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shattereddreamActionPerformed(evt);
            }
        });

        santo.setText("Santo");
        santo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                santoActionPerformed(evt);
            }
        });

        secondserve.setText("Second Serve");
        secondserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondserveActionPerformed(evt);
            }
        });

        soundwave.setText("Soundwave");
        soundwave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundwaveActionPerformed(evt);
            }
        });

        pomp.setText("Grapefruit");
        pomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pompActionPerformed(evt);
            }
        });

        stationhill.setText("Station Hill");
        stationhill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationhillActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("IPA/APA");

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Lager");

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Stout");

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Sour");

        brokendream.setText("Broken Dream");
        brokendream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brokendreamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SirenBeersLayout = new javax.swing.GroupLayout(SirenBeers);
        SirenBeers.setLayout(SirenBeersLayout);
        SirenBeersLayout.setHorizontalGroup(
            SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SirenBeersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addComponent(twothirds, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(half, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)
                        .addComponent(onethird, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(soundwave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lumina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(mesmerist, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(santo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stationhill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brokendream, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shattereddream, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pomp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondserve, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        SirenBeersLayout.setVerticalGroup(
            SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SirenBeersLayout.createSequentialGroup()
                .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twothirds, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(half, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onethird, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pomp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondserve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brokendream, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pastel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stationhill, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shattereddream, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soundwave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(santo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesmerist, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lumina, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Beers.addTab("Siren", SirenBeers);

        javax.swing.GroupLayout GuestBeersLayout = new javax.swing.GroupLayout(GuestBeers);
        GuestBeers.setLayout(GuestBeersLayout);
        GuestBeersLayout.setHorizontalGroup(
            GuestBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        GuestBeersLayout.setVerticalGroup(
            GuestBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Beers.addTab("Guest", GuestBeers);

        javax.swing.GroupLayout CansLayout = new javax.swing.GroupLayout(Cans);
        Cans.setLayout(CansLayout);
        CansLayout.setHorizontalGroup(
            CansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CansLayout.setVerticalGroup(
            CansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Beers.addTab("Cans", Cans);

        javax.swing.GroupLayout beersLayout = new javax.swing.GroupLayout(beers);
        beers.setLayout(beersLayout);
        beersLayout.setHorizontalGroup(
            beersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Beers)
        );
        beersLayout.setVerticalGroup(
            beersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Beers)
        );

        drinks.addTab("Beers", beers);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        drinks.addTab("Ciders", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        drinks.addTab("Wines", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        drinks.addTab("Soft/Hot", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drinks)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drinks)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pompActionPerformed
        addBeer("Grapefruit");
    }//GEN-LAST:event_pompActionPerformed

    private void secondserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondserveActionPerformed
        addBeer("SecondServe");
    }//GEN-LAST:event_secondserveActionPerformed

    private void luminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luminaActionPerformed
       addBeer("Lumina"); 
    }//GEN-LAST:event_luminaActionPerformed

    private void onethirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onethirdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onethirdActionPerformed

    private void halfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halfActionPerformed

    private void twothirdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twothirdsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twothirdsActionPerformed

    private void soundwaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundwaveActionPerformed
        addBeer("Soundwave");
    }//GEN-LAST:event_soundwaveActionPerformed

    private void mesmeristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesmeristActionPerformed
        addBeer("Mesmerist");
    }//GEN-LAST:event_mesmeristActionPerformed

    private void pastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastelActionPerformed
        addBeer("Pastel");
    }//GEN-LAST:event_pastelActionPerformed

    private void stationhillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationhillActionPerformed
        addBeer("StationHill");
    }//GEN-LAST:event_stationhillActionPerformed

    private void santoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_santoActionPerformed
        addBeer("Santo");
    }//GEN-LAST:event_santoActionPerformed

    private void brokendreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brokendreamActionPerformed
        addBeer("BrokenDream");
    }//GEN-LAST:event_brokendreamActionPerformed

    private void shattereddreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shattereddreamActionPerformed
        addBeer("ShatteredDream");
    }//GEN-LAST:event_shattereddreamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Beers;
    private javax.swing.JPanel Cans;
    private javax.swing.JPanel GuestBeers;
    private javax.swing.JPanel SirenBeers;
    private javax.swing.JPanel beers;
    private javax.swing.JButton brokendream;
    private javax.swing.JTabbedPane drinks;
    private javax.swing.JButton half;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton lumina;
    private javax.swing.JButton mesmerist;
    private javax.swing.JButton onethird;
    private javax.swing.JButton pastel;
    private javax.swing.JButton pomp;
    private javax.swing.JButton santo;
    private javax.swing.JButton secondserve;
    private javax.swing.JButton shattereddream;
    private javax.swing.JButton soundwave;
    private javax.swing.JButton stationhill;
    private javax.swing.JButton twothirds;
    // End of variables declaration//GEN-END:variables
}
