/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package drinks;

import till.main;
/**
 *
 * @author gabri
 */
public class drinks extends javax.swing.JPanel {
    private main parent;
    /**
     * Creates new form beer
     */
    public drinks(main parent) {
        initComponents();
        this.parent = parent; // Reference to main
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        drinks = new javax.swing.JTabbedPane();
        beers = new javax.swing.JPanel();
        Beers = new javax.swing.JTabbedPane();
        SirenBeers = new javax.swing.JPanel();
        twothirds = new javax.swing.JButton();
        half = new javax.swing.JButton();
        onethird = new javax.swing.JButton();
        javax.swing.JButton lumina = new javax.swing.JButton();
        javax.swing.JButton mesmerist = new javax.swing.JButton();
        javax.swing.JButton pastel = new javax.swing.JButton();
        javax.swing.JButton shattereddream = new javax.swing.JButton();
        javax.swing.JButton santo = new javax.swing.JButton();
        javax.swing.JButton secondserve = new javax.swing.JButton();
        javax.swing.JButton soundwave = new javax.swing.JButton();
        javax.swing.JButton pomp = new javax.swing.JButton();
        javax.swing.JButton stationhill = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        javax.swing.JButton brokendream = new javax.swing.JButton();
        GuestBeers = new javax.swing.JPanel();
        twothirds1 = new javax.swing.JButton();
        half1 = new javax.swing.JButton();
        onethird1 = new javax.swing.JButton();
        javax.swing.JButton guest1 = new javax.swing.JButton();
        javax.swing.JButton guest3 = new javax.swing.JButton();
        javax.swing.JButton guest2 = new javax.swing.JButton();
        javax.swing.JButton guest4 = new javax.swing.JButton();
        Cans = new javax.swing.JPanel();
        Ciders = new javax.swing.JPanel();
        SirenBeers1 = new javax.swing.JPanel();
        twothirds2 = new javax.swing.JButton();
        half2 = new javax.swing.JButton();
        onethird2 = new javax.swing.JButton();
        javax.swing.JButton applecider = new javax.swing.JButton();
        javax.swing.JButton cherrycider = new javax.swing.JButton();
        wines = new javax.swing.JPanel();
        mediumwine = new javax.swing.JButton();
        smallwine = new javax.swing.JButton();
        largewine = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        javax.swing.JButton merlot = new javax.swing.JButton();
        javax.swing.JButton pinotNoir = new javax.swing.JButton();
        javax.swing.JButton malbec = new javax.swing.JButton();
        javax.swing.JButton sauvignonBlanc = new javax.swing.JButton();
        javax.swing.JButton viognier = new javax.swing.JButton();
        javax.swing.JButton pinotGrigio = new javax.swing.JButton();
        javax.swing.JButton frenchRose = new javax.swing.JButton();
        spirits = new javax.swing.JPanel();
        doubleShot = new javax.swing.JButton();
        singleShot = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        javax.swing.JButton whiteGin = new javax.swing.JButton();
        javax.swing.JButton whiteRum = new javax.swing.JButton();
        javax.swing.JButton bourbon = new javax.swing.JButton();
        javax.swing.JButton absolut = new javax.swing.JButton();
        javax.swing.JButton pinkGin = new javax.swing.JButton();
        javax.swing.JButton foreignWhisky = new javax.swing.JButton();
        javax.swing.JButton spicedRum = new javax.swing.JButton();
        softDrinks = new javax.swing.JPanel();
        javax.swing.JButton coke = new javax.swing.JButton();
        javax.swing.JButton dietCoke = new javax.swing.JButton();
        javax.swing.JButton orangeJuice = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        twothirds.setText("2/3");
        twothirds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twothirdsActionPerformed(evt);
            }
        });

        half.setText("Half");
        half.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halfActionPerformed(evt);
            }
        });

        onethird.setText("1/3");
        onethird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onethirdActionPerformed(evt);
            }
        });

        lumina.setText("Lumina");
        lumina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luminaActionPerformed(evt);
            }
        });

        mesmerist.setText("Mesmerist");
        mesmerist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesmeristActionPerformed(evt);
            }
        });

        pastel.setText("Pastel");
        pastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastelActionPerformed(evt);
            }
        });

        shattereddream.setText("Shattered Dream");
        shattereddream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shattereddreamActionPerformed(evt);
            }
        });

        santo.setText("Santo");
        santo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                santoActionPerformed(evt);
            }
        });

        secondserve.setText("Second Serve");
        secondserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondserveActionPerformed(evt);
            }
        });

        soundwave.setText("Soundwave");
        soundwave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundwaveActionPerformed(evt);
            }
        });

        pomp.setText("Grapefruit");
        pomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pompActionPerformed(evt);
            }
        });

        stationhill.setText("Station Hill");
        stationhill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationhillActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("IPA/APA");

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Lager");

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Stout");

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Sour");

        brokendream.setText("Broken Dream");
        brokendream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brokendreamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SirenBeersLayout = new javax.swing.GroupLayout(SirenBeers);
        SirenBeers.setLayout(SirenBeersLayout);
        SirenBeersLayout.setHorizontalGroup(
            SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SirenBeersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addComponent(twothirds, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(half, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(onethird, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(mesmerist, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(lumina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soundwave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(santo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stationhill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brokendream, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shattereddream, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pomp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondserve, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE))))
        );
        SirenBeersLayout.setVerticalGroup(
            SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SirenBeersLayout.createSequentialGroup()
                .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twothirds, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(half, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onethird, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pomp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondserve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brokendream, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pastel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stationhill, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shattereddream, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soundwave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SirenBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(santo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesmerist, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SirenBeersLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lumina, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Beers.addTab("Siren", SirenBeers);

        twothirds1.setText("2/3");
        twothirds1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twothirds1ActionPerformed(evt);
            }
        });

        half1.setText("Half");
        half1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                half1ActionPerformed(evt);
            }
        });

        onethird1.setText("1/3");
        onethird1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onethird1ActionPerformed(evt);
            }
        });

        guest1.setText("Guest1");
        guest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guest1ActionPerformed(evt);
            }
        });

        guest3.setText("Guest3");
        guest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guest3ActionPerformed(evt);
            }
        });

        guest2.setText("Guest2");
        guest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guest2ActionPerformed(evt);
            }
        });

        guest4.setText("Guest4");
        guest4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guest4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GuestBeersLayout = new javax.swing.GroupLayout(GuestBeers);
        GuestBeers.setLayout(GuestBeersLayout);
        GuestBeersLayout.setHorizontalGroup(
            GuestBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuestBeersLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(GuestBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twothirds1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(guest2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(GuestBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GuestBeersLayout.createSequentialGroup()
                        .addComponent(half1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(onethird1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(GuestBeersLayout.createSequentialGroup()
                        .addGroup(GuestBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(guest4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guest3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        GuestBeersLayout.setVerticalGroup(
            GuestBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuestBeersLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(GuestBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twothirds1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(half1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onethird1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(GuestBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guest1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guest3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GuestBeersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guest4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guest2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(373, Short.MAX_VALUE))
        );

        Beers.addTab("Guest", GuestBeers);

        javax.swing.GroupLayout CansLayout = new javax.swing.GroupLayout(Cans);
        Cans.setLayout(CansLayout);
        CansLayout.setHorizontalGroup(
            CansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CansLayout.setVerticalGroup(
            CansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Beers.addTab("Cans", Cans);

        javax.swing.GroupLayout beersLayout = new javax.swing.GroupLayout(beers);
        beers.setLayout(beersLayout);
        beersLayout.setHorizontalGroup(
            beersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Beers)
        );
        beersLayout.setVerticalGroup(
            beersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Beers)
        );

        drinks.addTab("Beers", beers);

        twothirds2.setText("2/3");
        twothirds2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twothirds2ActionPerformed(evt);
            }
        });

        half2.setText("Half");
        half2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                half2ActionPerformed(evt);
            }
        });

        onethird2.setText("1/3");
        onethird2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onethird2ActionPerformed(evt);
            }
        });

        applecider.setText("Apple cider");
        applecider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleciderActionPerformed(evt);
            }
        });

        cherrycider.setText("Cherry cider");
        cherrycider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cherryciderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SirenBeers1Layout = new javax.swing.GroupLayout(SirenBeers1);
        SirenBeers1.setLayout(SirenBeers1Layout);
        SirenBeers1Layout.setHorizontalGroup(
            SirenBeers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SirenBeers1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(twothirds2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(half2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(onethird2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(SirenBeers1Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(applecider, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(cherrycider, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        SirenBeers1Layout.setVerticalGroup(
            SirenBeers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SirenBeers1Layout.createSequentialGroup()
                .addGroup(SirenBeers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twothirds2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(half2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onethird2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(SirenBeers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applecider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cherrycider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CidersLayout = new javax.swing.GroupLayout(Ciders);
        Ciders.setLayout(CidersLayout);
        CidersLayout.setHorizontalGroup(
            CidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SirenBeers1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CidersLayout.setVerticalGroup(
            CidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CidersLayout.createSequentialGroup()
                .addComponent(SirenBeers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 339, Short.MAX_VALUE))
        );

        drinks.addTab("Ciders", Ciders);

        mediumwine.setText("175ml");
        mediumwine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumwineActionPerformed(evt);
            }
        });

        smallwine.setText("125ml");
        smallwine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallwineActionPerformed(evt);
            }
        });

        largewine.setText("250ml");
        largewine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largewineActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("White");

        jTextField6.setEditable(false);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Red");

        jTextField7.setEditable(false);
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("Rose");

        merlot.setText("Merlot");
        merlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merlotActionPerformed(evt);
            }
        });

        pinotNoir.setText("Pinot noir");
        pinotNoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinotNoirActionPerformed(evt);
            }
        });

        malbec.setText("Malbec");
        malbec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malbecActionPerformed(evt);
            }
        });

        sauvignonBlanc.setText("Sauvignon Blanc");
        sauvignonBlanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvignonBlancActionPerformed(evt);
            }
        });

        viognier.setText("Viognier");
        viognier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viognierActionPerformed(evt);
            }
        });

        pinotGrigio.setText("Pinot Grigio");
        pinotGrigio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinotGrigioActionPerformed(evt);
            }
        });

        frenchRose.setText("French Rose");
        frenchRose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchRoseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winesLayout = new javax.swing.GroupLayout(wines);
        wines.setLayout(winesLayout);
        winesLayout.setHorizontalGroup(
            winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(merlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(largewine, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(pinotNoir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(malbec, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addGroup(winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(winesLayout.createSequentialGroup()
                        .addComponent(mediumwine, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(smallwine, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(winesLayout.createSequentialGroup()
                        .addGroup(winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viognier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pinotGrigio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sauvignonBlanc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(85, 85, 85)
                        .addGroup(winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7)
                            .addComponent(frenchRose, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        winesLayout.setVerticalGroup(
            winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediumwine, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallwine, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(largewine, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winesLayout.createSequentialGroup()
                        .addComponent(malbec, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(merlot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winesLayout.createSequentialGroup()
                        .addGroup(winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sauvignonBlanc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frenchRose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pinotGrigio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(winesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pinotNoir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viognier, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        drinks.addTab("Wines", wines);

        doubleShot.setText("50ml");
        doubleShot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleShotActionPerformed(evt);
            }
        });

        singleShot.setText("25ml");
        singleShot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleShotActionPerformed(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Whisky");

        jTextField9.setEditable(false);
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("Gin");

        jTextField10.setEditable(false);
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Vodka");

        jTextField11.setEditable(false);
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("Rum");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        whiteGin.setText("White");
        whiteGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteGinActionPerformed(evt);
            }
        });

        whiteRum.setText("White rum");
        whiteRum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteRumActionPerformed(evt);
            }
        });

        bourbon.setText("Bourbon");
        bourbon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bourbonActionPerformed(evt);
            }
        });

        absolut.setText("Absolut");
        absolut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absolutActionPerformed(evt);
            }
        });

        pinkGin.setText("Pink");
        pinkGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinkGinActionPerformed(evt);
            }
        });

        foreignWhisky.setText("Foreign whisky");
        foreignWhisky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foreignWhiskyActionPerformed(evt);
            }
        });

        spicedRum.setText("Spiced rum");
        spicedRum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spicedRumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout spiritsLayout = new javax.swing.GroupLayout(spirits);
        spirits.setLayout(spiritsLayout);
        spiritsLayout.setHorizontalGroup(
            spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spiritsLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spiritsLayout.createSequentialGroup()
                        .addGroup(spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9)
                            .addComponent(whiteGin, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(pinkGin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField11)
                            .addComponent(whiteRum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spicedRum, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField8)
                            .addComponent(foreignWhisky)
                            .addComponent(bourbon, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField10)
                            .addComponent(absolut, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spiritsLayout.createSequentialGroup()
                        .addComponent(doubleShot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(singleShot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        spiritsLayout.setVerticalGroup(
            spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spiritsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doubleShot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(singleShot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whiteGin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whiteRum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bourbon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(absolut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pinkGin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(spiritsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spicedRum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foreignWhisky, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        drinks.addTab("Spirits", spirits);

        coke.setText("Coke");
        coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeActionPerformed(evt);
            }
        });

        dietCoke.setText("Diet coke");
        dietCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietCokeActionPerformed(evt);
            }
        });

        orangeJuice.setText("Orange Juice");
        orangeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeJuiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout softDrinksLayout = new javax.swing.GroupLayout(softDrinks);
        softDrinks.setLayout(softDrinksLayout);
        softDrinksLayout.setHorizontalGroup(
            softDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(softDrinksLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(softDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dietCoke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orangeJuice, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap(711, Short.MAX_VALUE))
        );
        softDrinksLayout.setVerticalGroup(
            softDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(softDrinksLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(coke, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dietCoke, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orangeJuice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        drinks.addTab("Soft/Hot", softDrinks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drinks)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drinks)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pompActionPerformed
        parent.addDrink("Grape Fruit", "beer");
    }//GEN-LAST:event_pompActionPerformed

    private void secondserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondserveActionPerformed
        parent.addDrink("Second Serve", "beer");
    }//GEN-LAST:event_secondserveActionPerformed

    private void luminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luminaActionPerformed
        parent.addDrink("Lumina", "beer"); 
    }//GEN-LAST:event_luminaActionPerformed

    private void onethirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onethirdActionPerformed
        parent.setDrinksSize("1/3");
    }//GEN-LAST:event_onethirdActionPerformed

    private void halfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halfActionPerformed
        parent.setDrinksSize("Half");
    }//GEN-LAST:event_halfActionPerformed

    private void twothirdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twothirdsActionPerformed
        parent.setDrinksSize("2/3");
    }//GEN-LAST:event_twothirdsActionPerformed

    private void soundwaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundwaveActionPerformed
        parent.addDrink("Soundwave", "beer");
    }//GEN-LAST:event_soundwaveActionPerformed

    private void mesmeristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesmeristActionPerformed
        parent.addDrink("Mesmerist", "beer");
    }//GEN-LAST:event_mesmeristActionPerformed

    private void pastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastelActionPerformed
        parent.addDrink("Pastel", "beer");
    }//GEN-LAST:event_pastelActionPerformed

    private void stationhillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationhillActionPerformed
        parent.addDrink("Station Hill", "beer");
    }//GEN-LAST:event_stationhillActionPerformed

    private void santoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_santoActionPerformed
        parent.addDrink("Santo", "beer");
    }//GEN-LAST:event_santoActionPerformed

    private void brokendreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brokendreamActionPerformed
        parent.addDrink("Broken Dream", "beer");
    }//GEN-LAST:event_brokendreamActionPerformed

    private void shattereddreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shattereddreamActionPerformed
        parent.addDrink("Shattered Dream", "beer");
    }//GEN-LAST:event_shattereddreamActionPerformed

    private void twothirds1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twothirds1ActionPerformed
        parent.setDrinksSize("2/3");
    }//GEN-LAST:event_twothirds1ActionPerformed

    private void half1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_half1ActionPerformed
        parent.setDrinksSize("Half");
    }//GEN-LAST:event_half1ActionPerformed

    private void onethird1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onethird1ActionPerformed
        parent.setDrinksSize("1/3");
    }//GEN-LAST:event_onethird1ActionPerformed

    private void guest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guest1ActionPerformed

    private void guest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guest3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guest3ActionPerformed

    private void guest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guest2ActionPerformed

    private void guest4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guest4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guest4ActionPerformed

    private void twothirds2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twothirds2ActionPerformed
        parent.setDrinksSize("2/3");
    }//GEN-LAST:event_twothirds2ActionPerformed

    private void half2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_half2ActionPerformed
        parent.setDrinksSize("Half");
    }//GEN-LAST:event_half2ActionPerformed

    private void onethird2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onethird2ActionPerformed
        parent.setDrinksSize("1/3");
    }//GEN-LAST:event_onethird2ActionPerformed

    private void appleciderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleciderActionPerformed
        parent.addDrink("Apple Cider", "cider");
    }//GEN-LAST:event_appleciderActionPerformed

    private void cherryciderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cherryciderActionPerformed
        parent.addDrink("Cherry Cider", "cider");
    }//GEN-LAST:event_cherryciderActionPerformed

    private void mediumwineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumwineActionPerformed
        parent.setDrinksSize("175ml");
    }//GEN-LAST:event_mediumwineActionPerformed

    private void doubleShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleShotActionPerformed
        parent.setDrinksSize("50ml");
    }//GEN-LAST:event_doubleShotActionPerformed

    private void singleShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleShotActionPerformed
        parent.setDrinksSize("25ml");
    }//GEN-LAST:event_singleShotActionPerformed

    private void largewineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largewineActionPerformed
        parent.setDrinksSize("250ml");
    }//GEN-LAST:event_largewineActionPerformed

    private void smallwineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallwineActionPerformed
        parent.setDrinksSize("125ml");
    }//GEN-LAST:event_smallwineActionPerformed

    private void malbecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malbecActionPerformed
        parent.addDrink("Malbec", "wine");
    }//GEN-LAST:event_malbecActionPerformed

    private void merlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merlotActionPerformed
        parent.addDrink("Merlot", "wine");
    }//GEN-LAST:event_merlotActionPerformed

    private void pinotNoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinotNoirActionPerformed
        parent.addDrink("Pinot Noir", "wine");
    }//GEN-LAST:event_pinotNoirActionPerformed

    private void sauvignonBlancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvignonBlancActionPerformed
        parent.addDrink("Sauvignon Blanc", "wine");
    }//GEN-LAST:event_sauvignonBlancActionPerformed

    private void pinotGrigioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinotGrigioActionPerformed
        parent.addDrink("Pinot Grigio", "wine");
    }//GEN-LAST:event_pinotGrigioActionPerformed

    private void viognierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viognierActionPerformed
        parent.addDrink("Viognier", "wine");
    }//GEN-LAST:event_viognierActionPerformed

    private void frenchRoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchRoseActionPerformed
        parent.addDrink("French Rose", "wine");
    }//GEN-LAST:event_frenchRoseActionPerformed

    private void whiteGinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteGinActionPerformed
        parent.addDrink("White Gin", "spirit");
    }//GEN-LAST:event_whiteGinActionPerformed

    private void pinkGinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkGinActionPerformed
        parent.addDrink("Pink Gin", "spirit");
    }//GEN-LAST:event_pinkGinActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void whiteRumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteRumActionPerformed
        parent.addDrink("White Rum", "spirit");
    }//GEN-LAST:event_whiteRumActionPerformed

    private void spicedRumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spicedRumActionPerformed
        parent.addDrink("Spiced Rum", "spirit");
    }//GEN-LAST:event_spicedRumActionPerformed

    private void bourbonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bourbonActionPerformed
        parent.addDrink("Bourbon", "spirit");
    }//GEN-LAST:event_bourbonActionPerformed

    private void foreignWhiskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foreignWhiskyActionPerformed
        parent.addDrink("Foreign Whisky", "spirit");
    }//GEN-LAST:event_foreignWhiskyActionPerformed

    private void absolutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absolutActionPerformed
        parent.addDrink("Absolut", "spirit");
    }//GEN-LAST:event_absolutActionPerformed

    private void cokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeActionPerformed
        parent.addDrink("Coke", "soft");
    }//GEN-LAST:event_cokeActionPerformed

    private void dietCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietCokeActionPerformed
        parent.addDrink("Diet Coke", "soft");
    }//GEN-LAST:event_dietCokeActionPerformed

    private void orangeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeJuiceActionPerformed
        parent.addDrink("Orange Juice", "soft");
    }//GEN-LAST:event_orangeJuiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Beers;
    private javax.swing.JPanel Cans;
    private javax.swing.JPanel Ciders;
    private javax.swing.JPanel GuestBeers;
    private javax.swing.JPanel SirenBeers;
    private javax.swing.JPanel SirenBeers1;
    private javax.swing.JPanel beers;
    private javax.swing.JButton doubleShot;
    private javax.swing.JTabbedPane drinks;
    private javax.swing.JButton half;
    private javax.swing.JButton half1;
    private javax.swing.JButton half2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton largewine;
    private javax.swing.JButton mediumwine;
    private javax.swing.JButton onethird;
    private javax.swing.JButton onethird1;
    private javax.swing.JButton onethird2;
    private javax.swing.JButton singleShot;
    private javax.swing.JButton smallwine;
    private javax.swing.JPanel softDrinks;
    private javax.swing.JPanel spirits;
    private javax.swing.JButton twothirds;
    private javax.swing.JButton twothirds1;
    private javax.swing.JButton twothirds2;
    private javax.swing.JPanel wines;
    // End of variables declaration//GEN-END:variables
}
