/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package desserts;

/**
 *
 * @author gabri
 */
public class desserts extends javax.swing.JPanel {

    /**
     * Creates new form desserts
     */
    public desserts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        snacks = new javax.swing.JButton();
        snacks1 = new javax.swing.JButton();
        snacks2 = new javax.swing.JButton();

        snacks.setText("Small plates");
        snacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snacksActionPerformed(evt);
            }
        });

        snacks1.setText("Small plates");
        snacks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snacks1ActionPerformed(evt);
            }
        });

        snacks2.setText("Small plates");
        snacks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snacks2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(snacks, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snacks1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snacks2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(snacks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snacks1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snacks2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void snacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snacksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snacksActionPerformed

    private void snacks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snacks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snacks1ActionPerformed

    private void snacks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snacks2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snacks2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton snacks;
    private javax.swing.JButton snacks1;
    private javax.swing.JButton snacks2;
    // End of variables declaration//GEN-END:variables
}
